### ISSUE TITLE
Linting configuration command innacurate

### ISSUE THREAD

**Issue by KasonBraley** [redpanda-data/rp-connect-docs#8]
### Issue description

The command to run the linter in this section does not work: https://docs.redpanda.com/redpanda-connect/configuration/about/#linting

`rpk connect run lint` give the error : `A maximum of one config must be specified with the run command`

The command looks like it should just be `rpk connect lint`, no `run` subcommand.

### Updates to existing documentation

https://docs.redpanda.com/redpanda-connect/configuration/about/#linting

**Comment by KasonBraley** [comment]
The same also applies to the section above it.

`rpk connect run create --help` does not exist, it should be `rpk connect create --help`.

**Comment by JakeSCahill** [comment]
Thanks @KasonBraley
